 Let's talk a bit about how NumPy arrays are different from Python containers.

You may have heard Python variables described as labels. They are not little cubbies in computer memory, ready to receive a value. Rather, the values are independent objects with their own space in memory, and a Python variable just points there; it's a name for that object. You can have more than one variable referring to the same object. This mechanism is very flexible, and it also allows for lists and dictionaries with heterogeneous elements. However, doing that is not very efficient when you are dealing with lots of values of the same type.

In that case, you may want to reserve a space in memory and just lay down all those values side by side. That's what a NumPy array is. Organizing data in this way is both faster, and more memory efficient. It's also necessary to interface Python with other languages such as C or Fortran, which count on data being laid out in memory in a simple fashion.

Since, all the data items in an array need to have the same size, NumPy needs to be very precise about identifying data types.

In this sense, it's more precise than Python: while Python has just one type of integer, and one type of floating-point number, NumPy has several. This is also needed to interface with C or Fortran. So, NumPy identifies several types of integers, depending on the number of bits that they take in their memorial presentation. numpy.int8, numpy.int16, numpy.int32, numpy.int64. The most common of this is numpy.int32. There are also unsigned varieties of these integers.

Similarly, for floating-point numbers, where the most common type is numpy.float64, a double precision floating-point number, which is the same as a standard Python float. There are other, more specialized types, such as boolean, true or false, string and unicode string, which are the same as in Python, but for which, in NumPy, you need to specify the length in advance; NumPy Void, which lets you put together composite types made of different pieces; and NumPy Object, which is a bit of an exception, because it lets you refer to any type of Python object.

In [1]:
import numpy as np    #specify abbreviation since we will be referring to numpy a lot
import matplotlib.pyplot as pp

In [2]:
# Creating a numpy array by converting a python list

a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [3]:
a.dtype

dtype('int64')

In [7]:
# We could also specify the datatype while creating the array

a = np.array([1,2,3,4,5],dtype=np.float64)

a

array([ 1.,  2.,  3.,  4.,  5.])

In [8]:
a.ndim, a.shape, a.size

(1, (5,), 5)

In [9]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10]],dtype=np.float64)

In [10]:
b.dtype

dtype('float64')

In [11]:
b.ndim, b.shape, b.size

(2, (2, 5), 10)

In [13]:
np.zeros((3,3),'d')   #'d' for double/float64

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [18]:
np.empty((3,3),'d')      #empty array with residual values in it

array([[  2.68156159e+154,   1.29074377e-231,   2.17464419e-314],
       [  2.17463967e-314,   2.17568230e-314,   2.18005997e-314],
       [  2.14426941e-314,   2.18072289e-314,   2.17557680e-314]])

We can also create regularly spaced arrays of numbers.
We can either choose the number of elements between two extrema, such as five elements between zero and 10, included them

In [19]:
np.linspace(0,10,5)

array([  0. ,   2.5,   5. ,   7.5,  10. ])

Or you can choose the step to use to go between these two elements, such as increase by two, go in between zero and 10.

In [20]:
np.arange(0,10,2)    

array([0, 2, 4, 6, 8])

In [21]:
np.random.standard_normal((2,4))

array([[-0.70537052, -0.10992641,  1.13430326, -0.63776584],
       [-0.19267447, -1.54789955,  0.13257144,  0.91903218]])

In [22]:
# To stack two arrays on top of each other 
# use numpy.vstack

a = np.random.standard_normal((2,3))
b = np.random.standard_normal((2,3))

np.vstack([a,b])

array([[-0.19211684,  0.29715   ,  1.31980201],
       [-0.39607981,  1.42158343,  0.68257957],
       [-1.13590631, -0.09705556, -1.16254638],
       [ 0.66415181,  1.16575999, -0.90586073]])

In [23]:
np.hstack([a,b])

array([[-0.19211684,  0.29715   ,  1.31980201, -1.13590631, -0.09705556,
        -1.16254638],
       [-0.39607981,  1.42158343,  0.68257957,  0.66415181,  1.16575999,
        -0.90586073]])

In [24]:
# Transpose of an array

a.transpose()

array([[-0.19211684, -0.39607981],
       [ 0.29715   ,  1.42158343],
       [ 1.31980201,  0.68257957]])

In [25]:
#To save and load numpy arrays to and from disk

np.save('example.npy',a)   #give a name for file 'example.npy' and array to be saved(a)


In [26]:
al = np.load('example.npy')

In [27]:
al

array([[-0.19211684,  0.29715   ,  1.31980201],
       [-0.39607981,  1.42158343,  0.68257957]])