**How to index and slice NumPy arrays**

**Extensions to the Python indexing syntax that are available with NumPy**

**Differences between indexing and slicing in NumPy and in Python**

In [1]:
import numpy as np

In [16]:
#Indexing for 1D arrays

v = np.linspace(0,10,5)

v

array([  0. ,   2.5,   5. ,   7.5,  10. ])

In [3]:
v[1]

2.5

In [4]:
v[-1]

10.0

In [6]:
v[5]    #non-existent item

IndexError: index 5 is out of bounds for axis 0 with size 5

In [7]:
#Indexing for 2D arrays

vv = np.random.random((5,4))

In [8]:
vv

array([[ 0.33339329,  0.38527535,  0.3769696 ,  0.05645372],
       [ 0.11347696,  0.36883868,  0.14645742,  0.4747375 ],
       [ 0.87652054,  0.96021586,  0.58742702,  0.80448479],
       [ 0.583219  ,  0.79418938,  0.16128296,  0.80829356],
       [ 0.80747485,  0.9192573 ,  0.04975828,  0.17638074]])

In [9]:
vv[0,0]

0.33339328713297844

In [10]:
vv[4,3]

0.17638074340089216

This is different than we would do with Python lists. The closest analog to a two dimensional array that we could build with lists would be a list of lists such as

In [11]:
ll = [[1,2,3],[4,5,6],[7,8,9]]

In [12]:
ll[1,2]

TypeError: list indices must be integers or slices, not tuple

In [13]:
ll[1][2]

6

In [14]:
#Slicing of 1D array

v[2:4]

array([ 5. ,  7.5])

In [17]:
#Slicing of 2D array

vv[2]

array([ 0.87652054,  0.96021586,  0.58742702,  0.80448479])

In [18]:
vv[2:5,1]

array([ 0.96021586,  0.79418938,  0.9192573 ])

In [19]:
vv[2:5,1:2]

array([[ 0.96021586],
       [ 0.79418938],
       [ 0.9192573 ]])

In [20]:
vv[2:-1,:]

array([[ 0.87652054,  0.96021586,  0.58742702,  0.80448479],
       [ 0.583219  ,  0.79418938,  0.16128296,  0.80829356]])

In [21]:
vv[:,::2]

array([[ 0.33339329,  0.3769696 ],
       [ 0.11347696,  0.14645742],
       [ 0.87652054,  0.58742702],
       [ 0.583219  ,  0.16128296],
       [ 0.80747485,  0.04975828]])

One important difference though is that NumPy slices yield views onto the same piece of memory, so if we create a new array by slicing and modify its values, we end up modifying the original array. 

In [22]:
v2 =v[2:4]  #v2 is a small slice of 1D array

In [25]:
v2[0] = 0   #element 0 changed to 0

In [26]:
v    #that value has been changed in the original array as well

array([  0. ,   2.5,   0. ,   7.5,  10. ])

In [28]:
# if we need a copy, we need to explicitly make it in Numpy

v3 = v[2:4].copy()

In [29]:
v3[0] = 1

In [31]:
v

array([  0. ,   2.5,   0. ,   7.5,  10. ])

In [32]:
# ADVANCED INDEXING

# 1. We can use a list of indices or a numpy array of indices to select only certain elements

v[[1,2,3]]

array([ 2.5,  0. ,  7.5])

The other extension consists of using an array of Boolean values, true or false, to choose which elements to include and which not to. The easiest way to build such an array is with a comparison operator or in a quality operator.

In [34]:
v>0

array([False,  True, False,  True,  True], dtype=bool)

In [35]:
bool_index = v > 0

In [36]:
v[bool_index]

array([  2.5,   7.5,  10. ])

In [37]:
#  This kind of indexing is often used to modify only carefully selected parts of an array.

vv

array([[ 0.33339329,  0.38527535,  0.3769696 ,  0.05645372],
       [ 0.11347696,  0.36883868,  0.14645742,  0.4747375 ],
       [ 0.87652054,  0.96021586,  0.58742702,  0.80448479],
       [ 0.583219  ,  0.79418938,  0.16128296,  0.80829356],
       [ 0.80747485,  0.9192573 ,  0.04975828,  0.17638074]])

In [38]:
vv[vv > 0.5] = vv[vv > 0.5]*2

In [39]:
vv

array([[ 0.33339329,  0.38527535,  0.3769696 ,  0.05645372],
       [ 0.11347696,  0.36883868,  0.14645742,  0.4747375 ],
       [ 1.75304108,  1.92043172,  1.17485404,  1.60896959],
       [ 1.16643799,  1.58837876,  0.16128296,  1.61658712],
       [ 1.61494969,  1.83851461,  0.04975828,  0.17638074]])